#!/usr/bin/env node
/**
 * One-shot extractor (v1.3.0 pipeline migration).
 *
 * Reads the three v1.2.0 snapshot JSONs from themes/_snapshot/, walks them
 * in lockstep, and produces:
 *
 *   themes/_src/base.yaml
 *     The structural shell. Every leaf that has the same value across all
 *     three variants is written as a literal. Every leaf that differs is
 *     replaced with a ${token.name} reference whose name is derived from
 *     the JSON path (e.g. colors.editor.background → token "colors.editor.background").
 *
 *   themes/_src/variants/{alone,alone-soft,alone-focused}.yaml
 *     Per-variant token bindings: { display, filename, tokens: { ... } }.
 *
 * The token names are mechanical (path-based) by design; semantic renaming
 * can happen later without changing the pipeline. After this script runs,
 * `npm run build:themes` should produce JSON semantically identical to the
 * snapshots — `diff <(jq -S . built.json) <(jq -S . snapshot.json)` empty.
 * The raw text layout will differ because JSON.stringify always expands
 * multi-key objects; v1.2.0 had hand-formatted compact one-liners for some
 * small settings objects.
 *
 * This file is committed only for historical traceability of the v1.3.0
 * migration; it is not part of the build pipeline.
 *
 * Usage: node scripts/_extract-deltas.mjs
 */

import fs from 'node:fs';
import path from 'node:path';
import url from 'node:url';
import YAML from 'yaml';

const HERE = path.dirname(url.fileURLToPath(import.meta.url));
const ROOT = path.join(HERE, '..');
const SNAP = path.join(ROOT, 'themes', '_snapshot');
const SRC = path.join(ROOT, 'themes', '_src');

const VARIANT_FILES = {
  'alone': 'alone-color-theme.json',
  'alone-soft': 'alone-soft-color-theme.json',
  'alone-focused': 'alone-focused-color-theme.json',
};

const themes = Object.fromEntries(
  Object.entries(VARIANT_FILES).map(([key, fname]) => [
    key,
    JSON.parse(fs.readFileSync(path.join(SNAP, fname), 'utf8')),
  ])
);

// tokenName -> { alone, 'alone-soft', 'alone-focused' }
const tokens = new Map();

function pathToTokenName(pathArr) {
  // Numeric path components (array indices) — keep as is, joined with dots.
  // Special-case the tokenColors array: use the entry's `name` field for
  // stable, readable token names rather than positional indices.
  const segs = [];
  for (let i = 0; i < pathArr.length; i++) {
    const seg = pathArr[i];
    if (pathArr[0] === 'tokenColors' && i === 1 && typeof seg === 'number') {
      const entry = themes.alone.tokenColors[seg];
      // Slugify the entry name for token-id use.
      const slug = (entry?.name ?? `idx${seg}`)
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_|_$/g, '');
      segs.push(slug);
    } else {
      segs.push(String(seg));
    }
  }
  return segs.join('.');
}

function getAt(obj, pathArr) {
  return pathArr.reduce((o, k) => (o == null ? o : o[k]), obj);
}

function walk(pathArr) {
  const ref = getAt(themes.alone, pathArr);
  if (ref === null || ref === undefined) return ref;
  if (typeof ref !== 'object') {
    // Leaf scalar (string / number / boolean).
    const vals = {};
    for (const [name, obj] of Object.entries(themes)) {
      vals[name] = getAt(obj, pathArr);
    }
    const allEqual = Object.values(vals).every((v) => v === vals.alone);
    if (allEqual) return ref;
    const tokenName = pathToTokenName(pathArr);
    if (tokens.has(tokenName)) {
      // Collision (shouldn't happen since paths are unique); make it loud.
      throw new Error(`token name collision: ${tokenName}`);
    }
    tokens.set(tokenName, vals);
    return `\${${tokenName}}`;
  }
  if (Array.isArray(ref)) {
    return ref.map((_, i) => walk([...pathArr, i]));
  }
  const out = {};
  for (const k of Object.keys(ref)) {
    out[k] = walk([...pathArr, k]);
  }
  return out;
}

const base = walk([]);

// Write base.yaml. We want YAML output that preserves insertion order
// (Object.keys order is insertion order in modern Node, and YAML.stringify
// preserves that). We also want strings with leading `${...}` to be
// emitted as plain unquoted scalars when safe, or quoted otherwise — the
// yaml package handles this.
fs.mkdirSync(SRC, { recursive: true });
fs.writeFileSync(
  path.join(SRC, 'base.yaml'),
  '# Generated by scripts/_extract-deltas.mjs.\n' +
    '# Structural skeleton for all Alone theme variants. Leaves that vary\n' +
    '# across variants are written as ${token.name}; the variants/*.yaml\n' +
    '# files supply the per-variant bindings. Hand-edit with care: changes\n' +
    '# to the shape (keys, scopes, array order) propagate to every variant.\n\n' +
    YAML.stringify(base, { lineWidth: 0 })
);

fs.mkdirSync(path.join(SRC, 'variants'), { recursive: true });
for (const [variantName, fname] of Object.entries(VARIANT_FILES)) {
  const variantTokens = {};
  for (const [tokName, vals] of tokens) {
    variantTokens[tokName] = vals[variantName];
  }
  const doc = {
    display: themes[variantName].name,
    filename: fname,
    tokens: variantTokens,
  };
  fs.writeFileSync(
    path.join(SRC, 'variants', `${variantName}.yaml`),
    `# Generated by scripts/_extract-deltas.mjs.\n` +
      `# Per-variant token bindings for ${themes[variantName].name}.\n` +
      `# Token names are mechanical paths into the theme JSON; semantic\n` +
      `# renaming can happen later by editing base.yaml + all variant files\n` +
      `# in lockstep.\n\n` +
      YAML.stringify(doc, { lineWidth: 0 })
  );
}

console.log(`Wrote base.yaml + ${Object.keys(VARIANT_FILES).length} variant deltas.`);
console.log(`Total tokens (divergent leaves): ${tokens.size}`);
